[package]
name = "rust-database"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
futures = "0.3.31"
sqlx = { version = "0.8.3", features = ["runtime-tokio", "chrono", "postgres"] }
tokio = { version = "1.44.0", features = ["full"] }
